spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/tasks-db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: studyproject